# Generated by Django 3.2.5 on 2022-01-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.CharField(default=9999999, max_length=7, verbose_name='money'),
        ),
    ]
